INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Batsman', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Roman Powell', 'Batsman', 1.0, 91, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Tilak Verma', 'Batsman', 1.0 , 94, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Suryakumar Yadav', 'Batsman', 2.0 , 99, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('David Warner', 'Batsman', 2.0 , 94, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ajinkya Rahane', 'Batsman', 1.0 , 92, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Manish Pandey', 'Batsman', 2.0 , 91, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Prithvi Shaw', 'Batsman', 1.0 , 90, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Harry Brook', 'Batsman', 1.0 , 91, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rohit Sharma', 'Batsman', 2.0 , 100, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Tim David', 'Batsman', 1.0, 93, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Finn Allen', 'Batsman', 1.0 , 89, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shashank Singh', 'Batsman', 1.0 , 93, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rajat Patidar', 'Batsman', 0.5, 93, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mayank Agarwal', 'Batsman', 1.0, 92, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Nehal Wadhera', 'Batsman', 0.5, 89, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('David Malan', 'Batsman', 1.0 , 91, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rachin Ravindra', 'Batsman', 2.0 , 95, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shahrukh Khan', 'Batsman', 0.5, 88, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Nitish Rana ', 'Batsman', 1.0 , 93, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shreyas Iyer', 'Batsman', 1.0, 95, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Devdutt Padikkal', 'Batsman', 0.5, 90, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Sai Sudharsan ', 'Batsman', 0.5, 90, 1);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Batsman', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shimron Hetmyer', 'Batsman', 1.0 , 94, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Yashasvi Jaiswal', 'Batsman', 1.0 , 96, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Dhruv Jurel', 'Batsman', 1.0, 93, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Faf du Plessis', 'Batsman', 2.0 , 96, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Riyan Parag', 'Batsman', 1.0 , 93, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shikhar Dhawan', 'Batsman', 2.0 , 94, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rahul Tripathi', 'Batsman', 1.0 , 94, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Dewald Brewis', 'Batsman', 0.5, 89, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ruturaj Gaikwad', 'Batsman', 1.0, 95, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('David Miller', 'Batsman', 1.0, 93, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Travis Head', 'Batsman', 2.0 , 99, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Nicolas Pooran', 'Batsman', 2.0 , 95, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rinku Singh', 'Batsman', 2.0 , 97, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Will Jacks', 'Batsman', 1.0 , 92, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shubhman Gill', 'Batsman', 2.0 , 97, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jake Fraser-McGurk', 'Batsman', 1.0 , 93, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Aiden Markram', 'Batsman', 1.0 , 91, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Virat Kohli', 'Batsman', 2.0 , 100, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Suyash Prabhudessai', 'Batsman', 1.0 , 89, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kane Williamson', 'Batsman', 2.0 , 95, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Karun Nair', 'Batsman', 0.5, 91, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Glenn Phillips', 'Batsman', 1.0 , 92, 2);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Bowler', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kyle Jamieson', 'Bowler', 1.0 , 92, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ravi Bishnoi', 'Bowler', 2.0 , 96, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mohammed Siraj', 'Bowler', 2.0 , 95, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Sunil Narine', 'Bowler', 2.0 , 95, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Prasidh Krishna', 'Bowler', 1.0 , 92, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kagiso Rabada', 'Bowler', 2.0 , 96, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Anrich Nortje', 'Bowler', 2.0 , 95, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Gerald Coetzee', 'Bowler', 1.0 , 92, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Reece Topley', 'Bowler', 1.0 , 88, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Naveen ul haq', 'Bowler', 0.5, 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Avesh Khan', 'Bowler', 1.0 , 92, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Lockie Ferguson', 'Bowler', 2.0 , 95, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Adam Zampa', 'Bowler',1.0 , 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jaydev Unadkat', 'Bowler', 2.0 , 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jasprit Bumrah', 'Bowler', 3.0 , 100, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shardul Thakur', 'Bowler', 2.0 , 91, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mukesh Kumar', 'Bowler', 0.5 , 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('T Natarajan', 'Bowler', 1.0 , 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Noor Ahmad', 'Bowler', 1.0 , 93, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Navdeep Saini', 'Bowler', 0.5 , 88, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Matheesha Pathirana', 'Bowler', 1.0 , 94, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Khaleel Ahmed', 'Bowler', 0.5 , 88, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Tushar Deshpande', 'Bowler', 0.5, 88, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mitchell Starc', 'Bowler', 2.0 , 97, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mohammad Shami', 'Bowler', 2.0 , 98, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Umesh Yadav', 'Bowler', 1.0 , 90, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Urman Malik', 'Bowler', 1.0 , 89, 3);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Bowler', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Wanindu Hasaranga', 'Bowler', 2.0 , 94, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jofra archer', 'Bowler', 2.0 , 94, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Varun Chakravarthy', 'Bowler', 2.0 , 95, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Y Chahal', 'Bowler', 2.0 , 96, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kartik Tyagi', 'Bowler', 0.5 , 89, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Trent Boult', 'Bowler', 2.0 , 99, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rahul Chahar', 'Bowler', 1.0 , 89, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Amit Mishra', 'Bowler', 1.0 , 88, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Josh Hazlewood', 'Bowler', 2.0 , 96, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Piyush Chawla', 'Bowler', 1.0 , 88, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ravichandran Ashwin', 'Bowler', 2.0 , 95, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Maheesh Theekshana', 'Bowler', 2.0 , 93, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mohsin Khan', 'Bowler', 0.5 , 90, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Harshal Patel', 'Bowler', 2.0 , 94, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Arshdeep Singh', 'Bowler', 2.0 , 96, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ishant Sharma', 'Bowler', 2.0 , 89, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Lungi Ngidi', 'Bowler', 2.0 , 91, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Bhuvneshwar Kumar', 'Bowler', 2.0 , 97, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mark Wood', 'Bowler', 2.0 , 93, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mujeeb ur Rahman', 'Bowler', 2.0, 92, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mayank Markande', 'Bowler', 0.5, 89, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Deepak Chahar', 'Bowler', 1.0 , 94, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shahbaz Ahmed', 'Bowler', 0.5, 91, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kuldeep Yadav', 'Bowler', 2.0 , 97, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rashid Khan', 'Bowler', 2.0 , 99, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Arjun Tendulkar', 'Bowler', 0.5, 89, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mohit Sharma', 'Bowler', 1.0 , 95, 4);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Wicket Keeper', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Quinton de Kock', 'WK', 2.0 , 97, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Johnny Bairstow', 'WK', 2.0, 94, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rishabh Pant', 'WK', 2.0 , 96, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mahendra Singh Dhoni', 'WK', 2.0 , 100, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ishan Kishan', 'WK', 2.0 , 94, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Matthew Wade', 'WK', 2.0 , 93, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Heinrich Klaasen', 'WK', 2.0 , 98, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rahmanullah Gurbaz', 'WK', 1.0 , 92, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Phill Salt', 'WK', 2.0 , 95, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('KL Rahul', 'WK', 2.0 , 97, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Sanju Samson', 'WK', 2.0 , 95, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Devon Conway', 'WK', 2.0 , 95, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jos Buttler', 'WK', 2.0 , 99, 5);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('All Rounder', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Marcus Stoinis', 'All Rounders', 2.0 , 94, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ben Stokes', 'All Rounders', 2.0 , 94, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mitchell Santner', 'All Rounders', 1.0 , 95, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Andre Russell', 'All Rounders', 2.0 , 96, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Cameron Green ', 'All Rounders', 2.0 , 93, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shivam Dube', 'All Rounders', 0.5, 94, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('K Gowtham', 'All Rounders', 0.5, 89, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mohammad Nabi', 'All Rounders', 1.0 , 93, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Washington Sundar', 'All Rounders', 1.0 , 95, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Marco Jansen', 'All Rounders', 2.0 , 93, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Ravindra Jadeja', 'All Rounders', 2.0 , 97, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Liam Livingstone', 'All Rounders', 1.0 , 92, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Abhishek Sharma', 'All Rounders', 1.0 , 97, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Nitish Kumar Reddy', 'All Rounders', 1.0 , 95, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Axar Patel', 'All Rounders', 1.0 , 95, 6);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('All Rounder', 'Role', 'Base Price', Rating, Pot);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Venkatesh Iyer ', 'All Rounders', 1.0 , 92, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('David Willey', 'All Rounders', 1.0 , 89, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shakib Al Hasan', 'All Rounders', 1.0 , 91, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Deepak Hooda', 'All Rounders', 1.0 , 92, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Daryl Mitchell', 'All Rounders', 1.0 , 93, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Hardik Pandya', 'All Rounders', 2.0 , 97, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Rahul Tewatiya', 'All Rounders', 1.0 , 91, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Sam Curran', 'All Rounders', 1.0 , 96, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Moeen Ali', 'All Rounders', 1.0 , 94, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Mitchell Marsh', 'All Rounders', 1.0 , 92, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Patt Cummins', 'All Rounders', 2.0 , 98, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Chris Jordan', 'All Rounders', 0.5 , 88, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Glenn Maxwell', 'All Rounders', 2.0 , 93, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Krunal Pandya', 'All Rounders', 1.0 , 92, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Jason Holder', 'All Rounders', 1.0, 89, 7);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('nan', 'nan', 'nan', nan, nan);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Yuvraj Singh', 'Batsman', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Chris Gayle', 'Batsman', 2.0 , 100, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Lasith Malinga ', 'Bowler', 2.0 , 100, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Gautam Gambhir', 'Batsman', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Suresh Raina', 'Batsman', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Dwayne Bravo', 'All Rounders', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('AB De Villiers ', 'Batsman', 2.0 , 100, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shane Watson', 'All Rounders', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Kieron Pollard', 'Batsman', 2.0 , 98, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('M. Muralitharan', 'Bowler', 2.0 , 99, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Sachin Tendulkar', 'Batsman', 2.0 , 100, 8);
INSERT INTO players (pName, Role, basePrice, rating, pot) VALUES ('Shane Warne', 'Bowler', 2.0 , 99, 8);